data=[]
name=input().split('=')
data.append(name)
age=input().split('=')
data.append(age)
address=input().split('=')
data.append(address)
profession=input().split('=')
data.append(profession)
salary=input().split('=')
data.append(salary)
print(data)
print("type conversion")
d=dict(data)
print(d)
