l=[]
one=input().split()
two=input().split()
three=input().split()
four=input().split()
five=input().split()
l.append(one)
l.append(two)
l.append(three)
l.append(four)
l.append(five)
print("type of list we have created",type(1))
print(l)
d=dict(l)
print("here is your result as dictionary",d)
